name: Build Grasscutter

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/Grasscutters/Grasscutter.git
  BRANCH: development
  #BRANCH: stable

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
      
    - name: Clone code
      run: |
        java -version
        git clone -b "$BRANCH" "$REPO_URL"
        
    - name: Build
      run: |
        cd Grasscutter
        chmod +x gradlew
        ./gradlew
        ./gradlew jar
        
    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        path: ./grasscutter-*.jar
          
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 1
